# apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
# kind: Domain
# metadata:
#   # Corresponds to <federation> in the resource records.
#   name: raffa-apps
#   # The namespace running federation-controller-manager.
#   namespace: federation-system
# # The domain/subdomain that is setup in your externl-dns provider.
# domain: raffa-apps.systems
---
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  # The name of the sample service.
  name: bookinfo-ingressgateway
  # The namespace of the sample deployment/service.
  namespace: bookinfo
spec:
  # The name of the corresponding `Domain`.
  domainRef: raffa-apps
  recordTTL: 300
  dnsPrefix: bookinfo
           