apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: ["multiclusterdns.federation.k8s.io"] 
  resources: ["dnsendpoints","dnsendpoints/status"] 
  verbs: ["get","watch","list","patch","update"]  
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        # - --provider=rfc2136
        # - --rfc2136-host=10.9.53.20
        # - --rfc2136-port=53
        # - --rfc2136-zone=casl-contrib.osp.rht-labs.com
        # - --rfc2136-tsig-secret=aXf4BXuIRCWhVkOFz1wPsMr1BsZ811MnazxTG0HkUOM=
        # - --rfc2136-tsig-secret-alg=hmac-sha256
        # - --rfc2136-tsig-keyname=external-casl-contrib.osp.rht-labs.com
        # - --rfc2136-tsig-axfr 
        - --provider=coredns         
        - --registry=txt 
        - --txt-owner-id=raffa 
        - --source=crd 
        - --crd-source-apiversion=multiclusterdns.federation.k8s.io/v1alpha1 
        - --crd-source-kind=DNSEndpoint
        - --log-level=debug
        env:
        - name: ETCD_URLS
          value: http://coredns-etcd-client.external-dns.svc:2379 
      serviceAccountName: external-dns    
