apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: ["multiclusterdns.federation.k8s.io"] 
  resources: ["dnsendpoints","dnsendpoints/status"] 
  verbs: ["get","watch","list","patch","update"]  
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: {{ .Release.Namespace | quote }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args: 
        - --provider=coredns         
        - --registry=txt 
        - --txt-owner-id={{ .Values.txt_owner_id }} 
        - --source=crd 
        - --crd-source-apiversion=multiclusterdns.federation.k8s.io/v1alpha1 
        - --crd-source-kind=DNSEndpoint
        - --log-level={{ .Values.log_level }}
        - --kubeconfig=/etc/external-dns/kubeconfig
        env:
        - name: ETCD_URLS
          value: http://{{ .Values.etcd_name }}-client.{{ .Release.Namespace }}.svc:2379
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/external-dns
      volumes:
      - name: kubeconfig
        configMap:
          name: coredns-kubeconfig  
      serviceAccountName: external-dns    
