apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-kubeconfig
  namespace: {{ .Release.Namespace | quote }}
data:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
    - name: {{ .Values.cluster.name }}
      cluster:
        certificate-authority-data: {{ .Values.cluster.ca_data }}
        server: https://{{ .Values.cluster.url }}
    contexts:
    - name: {{ .Values.cluster.name }}
      context:
        cluster: {{ .Values.cluster.name }}
        user: {{ .Values.cluster.name }}  
    current-context: {{ .Values.cluster.name }}
    users:
    - name: {{ .Values.cluster.name }}
      user:
        token: {{ .Values.cluster.sa_token }}